support for WFRP4e system "worn/equipped" trappings flag
kandashi/Active-Token-Lighting pull request #128
Opened 2023-03-20 12:37 UTC by silentmark

Hi, 

this PR adds similar support for WFRP4e system that D&D5e already has. It allows to apply effects only when specific item is worn/equipped i.e. torch, lantern or other magic ring.

2023-03-31 20:56 UTC, kaelad02 reviewed
I looked at the WFRP4e system's code to see how it handles active effects. Instead of overriding the `isSuppressed` property like dnd5e does (although clumsily IMHO), it does its own filtering in `actorEffects` that is used when applying effects instead of the standard `effects` array as seen in the code linked below:

https://github.com/moo-man/WFRP4e-FoundryVTT/blob/master/modules/actor/actor-wfrp4e.js#L333

I think we should use the `actorEffects` function instead of handling the filtering on our own in the `ATL.applyEffects` function.

2023-03-31 20:56 UTC, kaelad02 commented on src/activeLighting.js
> +        const checkWfrpItemEquipped = (game.system.id === "wfrp4e");
I think we should remove this code and replace any `actor.effects` calls in the hooks with `actor.actorEffects` calls and let the system handle this filtering for us.

2023-04-02 05:32 UTC, silentmark commented on src/activeLighting.js
> +        const checkWfrpItemEquipped = (game.system.id === "wfrp4e");
If you would replace effects with actorEffects, no other changes in theory would be needed, as system already handles isEquipped flag when filtering effects

2023-04-10 02:39 UTC, kaelad02 requested changes
I only put suggested code for the `getEffects` function in 1/8 places. Please change it in the other 7 as well.

2023-04-10 02:39 UTC, kaelad02 commented on src/activeLighting.js
> +            let totalEffects = effect.parent.actorEffects.contents.filter(i => !i.disabled)
We can't just switch to `actorEffects` since that won't work for every other system. We'll need to do a check as to the system being used and either use `actor.actorEffects` if it's `wfrp4e` and `actor.effects` when it's not. I propose we add a small function to do that, then we can use it here:
```js
// I'd add this to the beginning of the `ready` function we're in
const getEffects = (actor) => {
    if (game.system.id === "wfrp4e") return actor?.actorEffects;
    return actor?.effects;
};
```
Then we can change lines like this to:
```suggestion
            let totalEffects = getEffects(effect.parent).contents.filter(i => !i.disabled)
```

2023-04-10 02:39 UTC, kaelad02 commented on src/activeLighting.js
>              if (game.userId !== userId) return;
For the proposed `getEffects` to work, we need to make sure this is an active effect on the actor and not an item. That check is done later in `ATL.applyEffects` but we need to check here first.
```suggestion
            if (game.userId !== userId || !(effect.parent instanceof Actor)) return;
```

2023-04-10 02:39 UTC, kaelad02 commented on src/activeLighting.js
>              if (game.userId !== userId) return;
```suggestion
            if (game.userId !== userId || !(effect.parent instanceof Actor)) return;
```

2023-04-10 02:39 UTC, kaelad02 commented on src/activeLighting.js
>              if (game.userId !== userId) return;
```suggestion
            if (game.userId !== userId || !(effect.parent instanceof Actor)) return;
```

2023-04-10 02:39 UTC, kaelad02 commented on src/activeLighting.js
> +            ATL.applyEffects(effect.parent, ATLeffects)
Why did you remove the `length` check here and a few other places?

2023-05-16 02:51 UTC, kaelad02 commented
@silentmark Can you address the review feedback I gave here?
https://github.com/kandashi/Active-Token-Lighting/pull/128#discussion_r1161390340
Having a `getEffects` function will make sure it works for WFRP4e as well as other systems. Plus, for v11 compatibility, I'll need a function like that anyways b/c of some changes in Foundry itself.

2023-05-16 08:01 UTC, silentmark commented
I will take a look into that end of this week

2023-06-28 02:43 UTC, kaelad02 commented
I'm going to make the changes I requested myself. I'll merge this into another branch, so your commits will still be there. Just gonna create another branch to put these in and then another PR to merge into main.

2023-06-28 02:50 UTC, kaelad02 commented
May not need to. I see "maintainers are allowed to edit this PR" so I should be able to commit myself

2023-06-28 02:51 UTC, kaelad02 commented on src/activeLighting.js
>          Hooks.on("updateActiveEffect", async (effect, change, options, userId) => {
```suggestion
        const getEffects = (actor) => {
            if (game.system.id === "wfrp4e") return actor?.actorEffects;
            return actor?.effects;
        };

        Hooks.on("updateActiveEffect", async (effect, change, options, userId) => {
```

2023-06-28 02:52 UTC, kaelad02 commented on src/activeLighting.js
> +            ATL.applyEffects(effect.parent, ATLeffects)
```suggestion
            if (ATLeffects.length > 0) ATL.applyEffects(effect.parent, ATLeffects)
```

2023-06-28 02:54 UTC, kaelad02 commented on src/activeLighting.js
> +            if (!effect.parent.actorEffects) return;
```suggestion
```

2023-06-28 02:55 UTC, kaelad02 commented on src/activeLighting.js
> +            const totalEffects = effect.parent.actorEffects.contents.filter(i => !i.disabled)
```suggestion
            const totalEffects = getEffects(effect.parent).contents.filter(i => !i.disabled)
```

2023-06-28 03:01 UTC, kaelad02 commented on src/activeLighting.js
> +                let ATLeffects = actor.actorEffects.filter(entity => !!entity.changes.find(effect => effect.key.includes("ATL")))
```suggestion
                let ATLeffects = getEffects(actor).filter(entity => !!entity.changes.find(effect => effect.key.includes("ATL")))
```

2023-06-28 03:01 UTC, kaelad02 commented on src/activeLighting.js
> +                ATL.applyEffects(actor, ATLeffects);
```suggestion
                if (ATLeffects.length > 0) ATL.applyEffects(actor, ATLeffects)
```

2023-06-28 03:01 UTC, kaelad02 commented on src/activeLighting.js
> +            let ATLeffects = token.actor?.actorEffects?.filter(entity => !!entity.changes.find(effect => effect.key.includes("ATL")))
```suggestion
            let ATLeffects = getEffects(token.actor)?.filter(entity => !!entity.changes.find(effect => effect.key.includes("ATL")))
```

2023-06-28 03:06 UTC, kaelad02 reviewed
one more line to remove

2023-06-28 03:06 UTC, kaelad02 commented on src/activeLighting.js
> +            if (!effect.parent.actorEffects) return;
```suggestion
```

2023-06-28 03:07 UTC, kaelad02 commented
I didn't realize I could commit to the PR. If I realized that earlier, I would have done this a lot sooner. I think I made all the changes I wanted. Does it look okay to you?

2023-06-28 03:07 UTC, kaelad02 approved these changes

2023-09-01 20:14 UTC, merged